DROP TABLE IF EXISTS sync_history;
DROP TABLE IF EXISTS erp_delivery;
DROP TABLE IF EXISTS erp_sales_order_item;
DROP TABLE IF EXISTS erp_sales_order;
DROP TABLE IF EXISTS erp_quote_item;
DROP TABLE IF EXISTS erp_quote;
DROP TABLE IF EXISTS erp_product;
DROP TABLE IF EXISTS erp_customer;

CREATE TABLE erp_customer (
    customer_code VARCHAR(30) PRIMARY KEY,
    customer_name VARCHAR(120) NOT NULL,
    business_no VARCHAR(30),
    email VARCHAR(120),
    phone VARCHAR(40),
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE erp_product (
    product_code VARCHAR(40) PRIMARY KEY,
    product_name VARCHAR(160) NOT NULL,
    category VARCHAR(80),
    unit_price DECIMAL(18,2) NOT NULL,
    active BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE erp_quote (
    quote_no VARCHAR(40) PRIMARY KEY,
    customer_code VARCHAR(30) NOT NULL,
    quote_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT fk_quote_customer FOREIGN KEY(customer_code) REFERENCES erp_customer(customer_code)
);

CREATE TABLE erp_quote_item (
    quote_no VARCHAR(40) NOT NULL,
    line_no INT NOT NULL,
    product_code VARCHAR(40) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(18,2) NOT NULL,
    PRIMARY KEY(quote_no, line_no),
    CONSTRAINT fk_quote_item_quote FOREIGN KEY(quote_no) REFERENCES erp_quote(quote_no)
);

CREATE TABLE erp_sales_order (
    order_no VARCHAR(40) PRIMARY KEY,
    quote_no VARCHAR(40),
    customer_code VARCHAR(30) NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_amount DECIMAL(18,2) NOT NULL,
    CONSTRAINT fk_order_customer FOREIGN KEY(customer_code) REFERENCES erp_customer(customer_code)
);

CREATE TABLE erp_sales_order_item (
    order_no VARCHAR(40) NOT NULL,
    line_no INT NOT NULL,
    product_code VARCHAR(40) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(18,2) NOT NULL,
    PRIMARY KEY(order_no, line_no),
    CONSTRAINT fk_order_item_order FOREIGN KEY(order_no) REFERENCES erp_sales_order(order_no)
);

CREATE TABLE erp_delivery (
    delivery_no VARCHAR(40) PRIMARY KEY,
    order_no VARCHAR(40) NOT NULL,
    shipped_at TIMESTAMP,
    carrier VARCHAR(80),
    tracking_no VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    CONSTRAINT fk_delivery_order FOREIGN KEY(order_no) REFERENCES erp_sales_order(order_no)
);

CREATE TABLE sync_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction VARCHAR(20) NOT NULL,
    entity_type VARCHAR(30) NOT NULL,
    external_key VARCHAR(80) NOT NULL,
    operation VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);
